### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by saiGo1992** [ymahlau/fdtdx#2]
When I use pip to install, come across error as show below:
![image](https://github.com/user-attachments/assets/71ffb18b-06e7-4321-acd4-9abaea92be6d)
How should I do to fix it? My operation system is windows10

**Comment by ymahlau** [comment]
Hi, 
thanks for bringing up this error. It seems that a C++-compiler has to be installed to install sharedarray with pip. I believe a quick way to circumvent this problem would be to use WSL and install FDTDX there. 

Note that JAX does not support the usage of GPU on windows machines. Your code will run very slow on windows machines.

That being said, I will see if it is possible to re-implement the code parts using sharedarray to remove this dependency. We only use sharedarray to generate videos for the simulations and this should not make installation unnecessarily complicated. This is probably only going to take a day or two, so expect to hear back from me shortly.

**Comment by ymahlau** [comment]
I removed the problematic dependency on sharedarray. If the problem still persists please let us know and reopen this issue!
